=== sugar-activities/4439-activity/resources/basis-link/share/dtd/officedocument/1_0/menubar.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--

  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
  
  Copyright 2008 by Sun Microsystems, Inc.
 
  OpenOffice.org - a multi-platform office productivity suite
 
  $RCSfile: menubar.dtd,v $
 
  $Revision: 1.3 $
 
  This file is part of OpenOffice.org.
 
  OpenOffice.org is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License version 3
  only, as published by the Free Software Foundation.
 
  OpenOffice.org is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Lesser General Public License version 3 for more details
  (a copy is included in the LICENSE file that accompanied this code).
 
  You should have received a copy of the GNU Lesser General Public License
  version 3 along with OpenOffice.org.  If not, see
  <http://www.openoffice.org/license.html>
  for a copy of the LGPLv3 License.
 
-->

<!ELEMENT menu:menubar (menu:menu+)>
<!ELEMENT menu:menu (menu:menupopup)>
<!ELEMENT menu:menupopup (menu:menuitem | menu:menuseparator | menu:menu)+>
<!ELEMENT menu:menuseparator EMPTY>
<!ELEMENT menu:menuitem EMPTY>
<!ATTLIST menu:menubar
	menu:id CDATA #REQUIRED
	xmlns:menu CDATA #FIXED "http://openoffice.org/2001/menu"
>
<!ATTLIST menu:menu
	menu:id CDATA #REQUIRED
	menu:label CDATA #IMPLIED
>
<!ATTLIST menu:menuitem
	menu:id CDATA #REQUIRED
	menu:helpid CDATA #IMPLIED
	menu:label CDATA #IMPLIED
>

=== sugar-activities/4439-activity/resources/basis-link/share/config/soffice.cfg/modules/swriter/menubar/menubar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu:menubar PUBLIC "-//OpenOffice.org//DTD OfficeDocument 1.0//EN" "menubar.dtd">
<menu:menubar xmlns:menu="http://openoffice.org/2001/menu" menu:id="menubar">
 <menu:menu menu:id=".uno:PickList" menu:label="">
  <menu:menupopup>
   <menu:menuitem menu:id=".uno:AddDirect"/>
   <menu:menuitem menu:id=".uno:Open"/>
   <menu:menuitem menu:id=".uno:RecentFileList"/>
   <menu:menuitem menu:id=".uno:CloseDoc"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:SaveAs"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:Reload"/>
   <menu:menuseparator/>
   <menu:menu menu:id=".uno:SendToMenu" menu:label="">
    <menu:menupopup>
     <menu:menuitem menu:id=".uno:SendMail"/>
    </menu:menupopup>
   </menu:menu>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:PrintPreview"/>
   <menu:menuitem menu:id=".uno:Print"/>
   <menu:menuitem menu:id=".uno:Quit"/> 
  </menu:menupopup>
 </menu:menu>
 <menu:menu menu:id=".uno:EditMenu" menu:label="">
  <menu:menupopup>
   <menu:menuitem menu:id=".uno:Undo"/>
   <menu:menuitem menu:id=".uno:Redo"/>
   <menu:menuitem menu:id=".uno:Repeat"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:Cut"/>
   <menu:menuitem menu:id=".uno:Copy"/>
   <menu:menuitem menu:id=".uno:Paste"/>
   <menu:menuitem menu:id=".uno:SelectAll"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:SearchDialog"/>
  </menu:menupopup>
 </menu:menu>
 <menu:menu menu:id=".uno:ViewMenu" menu:label="">
  <menu:menupopup>
   <menu:menuitem menu:id=".uno:PrintLayout"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:AvailableToolbars"/>
   <menu:menuitem menu:id=".uno:StatusBarVisible"/>
   <menu:menuitem menu:id=".uno:Ruler"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:ControlCodes"/>
   <menu:menuitem menu:id=".uno:ShowAnnotations"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:Zoom"/>
   <menu:menuseparator/>
   <menu:menu menu:id=".uno:ChangeUserLevel" menu:label="">
    <menu:menupopup>
     <menu:menuitem menu:id=".uno:SetUserLevelBeginner"/>
     <menu:menuitem menu:id=".uno:SetUserLevelAverage"/>
     <menu:menuitem menu:id=".uno:SetUserLevelExpert"/>
    </menu:menupopup>
   </menu:menu>
  </menu:menupopup>
 </menu:menu>
 <menu:menu menu:id=".uno:InsertMenu" menu:label="">
  <menu:menupopup>
   <menu:menuitem menu:id=".uno:InsertBreak"/>
   <menu:menu menu:id=".uno:FieldMenu" menu:label="">
    <menu:menupopup>
     <menu:menuitem menu:id=".uno:InsertDateField"/>
     <menu:menuitem menu:id=".uno:InsertTimeField"/>
     <menu:menuitem menu:id=".uno:InsertPageNumberField"/>
     <menu:menuitem menu:id=".uno:InsertPageCountField"/>
     <menu:menuitem menu:id=".uno:InsertTitleField"/>
     <menu:menuitem menu:id=".uno:InsertAuthorField"/>
     <menu:menuseparator/>
     <menu:menuitem menu:id=".uno:InsertField"/>
    </menu:menupopup>
   </menu:menu>
   <menu:menuitem menu:id=".uno:InsertSymbol"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:InsertPageHeader"/>
   <menu:menuitem menu:id=".uno:InsertPageFooter"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:InsertObjectStarMath"/>
   <menu:menuitem menu:id=".uno:InsertGraphic"/>
   <menu:menuitem menu:id=".uno:InsertAVMedia"/>
   <menu:menu menu:id=".uno:ObjectMenu" menu:label="">
    <menu:menupopup>
     <menu:menuitem menu:id=".uno:InsertObject"/>
     <menu:menuitem menu:id=".uno:InsertPlugin"/>
     <menu:menuitem menu:id=".uno:InsertObjectChart"/>
    </menu:menupopup>
   </menu:menu>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:InsertDoc"/>
  </menu:menupopup>
 </menu:menu>
 <menu:menu menu:id=".uno:FormatMenu" menu:label="">
  <menu:menupopup>
   <menu:menuitem menu:id=".uno:ResetAttributes"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:FontDialog"/>
   <menu:menuitem menu:id=".uno:ParagraphDialog"/>
   <menu:menuitem menu:id=".uno:PageDialog"/>
   <menu:menuseparator/>
   <menu:menu menu:id=".uno:TransliterateMenu" menu:label="">
    <menu:menupopup>
     <menu:menuitem menu:id=".uno:ChangeCaseToUpper"/>
     <menu:menuitem menu:id=".uno:ChangeCaseToLower"/>
    </menu:menupopup>
   </menu:menu>
   <menu:menuitem menu:id=".uno:FormatColumns"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:DesignerDialog"/>
   <menu:menuseparator/>
   <menu:menu menu:id=".uno:ObjectAlign" menu:label="">
    <menu:menupopup>
     <menu:menuitem menu:id=".uno:CommonAlignLeft"/>
     <menu:menuitem menu:id=".uno:CommonAlignHorizontalCenter"/>
     <menu:menuitem menu:id=".uno:CommonAlignRight"/>
     <menu:menuitem menu:id=".uno:CommonAlignJustified"/>
     <menu:menuseparator/>
     <menu:menuitem menu:id=".uno:CommonAlignTop"/>
     <menu:menuitem menu:id=".uno:CommonAlignVerticalCenter"/>
     <menu:menuitem menu:id=".uno:CommonAlignBottom"/>
    </menu:menupopup>
   </menu:menu>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:GraphicDialog"/>
  </menu:menupopup>
 </menu:menu>
 <menu:menu menu:id=".uno:ToolsMenu" menu:label="">
  <menu:menupopup>
   <menu:menuitem menu:id=".uno:SpellingAndGrammarDialog"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:ChapterNumberingDialog"/>
   <menu:menuitem menu:id=".uno:LineNumberingDialog"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:Gallery"/>
   <menu:menuseparator/>
   <menu:menu menu:id=".uno:UpdateMenu" menu:label="">
    <menu:menupopup>
     <menu:menuitem menu:id=".uno:UpdateAll"/>
    </menu:menupopup>
   </menu:menu>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:AutoCorrectDlg"/>
   <menu:menu menu:id=".uno:ScriptOrganizer"/>
   <menu:menuitem menu:id=".uno:ConfigureDialog"/>
   <menu:menuitem menu:id=".uno:OptionsTreeDialog"/>
  </menu:menupopup>
 </menu:menu>
 <menu:menu menu:id=".uno:WindowList" menu:label="">
  <menu:menupopup>
   <menu:menuitem menu:id=".uno:NewWindow"/>
   <menu:menuitem menu:id=".uno:CloseWin"/>
   <menu:menuseparator/>
  </menu:menupopup>
 </menu:menu>
 <menu:menu menu:id=".uno:HelpMenu" menu:label="">
  <menu:menupopup>
   <menu:menuitem menu:id=".uno:HelpIndex"/>
   <menu:menuitem menu:id=".uno:ExtendedHelp"/>
   <menu:menuitem menu:id=".uno:About"/>
   <menu:menuitem menu:id=".uno:ShowLicense"/>
  </menu:menupopup>
 </menu:menu>
</menu:menubar>

=== sugar-activities/4439-activity/resources/basis-link/share/config/soffice.cfg/modules/scalc/menubar/menubar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu:menubar PUBLIC "-//OpenOffice.org//DTD OfficeDocument 1.0//EN" "menubar.dtd">
<menu:menubar xmlns:menu="http://openoffice.org/2001/menu" menu:id="menubar">
 <menu:menu menu:id=".uno:PickList" menu:label="">
  <menu:menupopup>
   <menu:menuitem menu:id=".uno:AddDirect"/>
   <menu:menuitem menu:id=".uno:Open"/>
   <menu:menuitem menu:id=".uno:RecentFileList"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:CloseDoc"/>
   <menu:menuitem menu:id=".uno:SaveAs"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:Reload"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:ExportTo"/>
   <menu:menuitem menu:id=".uno:ExportToPDF"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:PrintPreview"/>
   <menu:menuitem menu:id=".uno:Print"/>
   <menu:menuitem menu:id=".uno:Quit"/>
  </menu:menupopup>
 </menu:menu>
 <menu:menu menu:id=".uno:EditMenu" menu:label="">
  <menu:menupopup>
   <menu:menuitem menu:id=".uno:Undo"/>
   <menu:menuitem menu:id=".uno:Redo"/>
   <menu:menuitem menu:id=".uno:Repeat"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:Cut"/>
   <menu:menuitem menu:id=".uno:Copy"/>
   <menu:menuitem menu:id=".uno:Paste"/>
   <menu:menuitem menu:id=".uno:PasteSpecial"/>
   <menu:menuitem menu:id=".uno:SelectAll"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:EditHeaderAndFooter"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:Delete"/>
   <menu:menuitem menu:id=".uno:DeleteCell"/>
   <menu:menu menu:id=".uno:EditSheetMenu" menu:label="">
    <menu:menupopup>
     <menu:menuitem menu:id=".uno:Move"/>
     <menu:menuitem menu:id=".uno:SelectTables"/>
     <menu:menuitem menu:id=".uno:Remove"/>
    </menu:menupopup>
   </menu:menu>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:ImageMapDialog"/>
   <menu:menuitem menu:id=".uno:ObjectMenue"/>
  </menu:menupopup>
 </menu:menu>
 <menu:menu menu:id=".uno:ViewMenu" menu:label="">
  <menu:menupopup>
   <menu:menuitem menu:id=".uno:NormalViewMode"/>
   <menu:menuitem menu:id=".uno:PagebreakMode"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:AvailableToolbars"/>
   <menu:menuitem menu:id=".uno:InputLineVisible"/>
   <menu:menuitem menu:id=".uno:StatusBarVisible"/>
   <menu:menuitem menu:id=".uno:ShowImeStatusWindow"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:ViewRowColumnHeaders"/>
   <menu:menuseparator/>
   <menu:menu menu:id=".uno:ChangeUserLevel" menu:label="">
    <menu:menupopup>
     <menu:menuitem menu:id=".uno:SetUserLevelBeginner"/>
     <menu:menuitem menu:id=".uno:SetUserLevelAverage"/>
     <menu:menuitem menu:id=".uno:SetUserLevelExpert"/>
    </menu:menupopup>
   </menu:menu>
  </menu:menupopup>
 </menu:menu>
 <menu:menu menu:id=".uno:InsertMenu" menu:label="">
  <menu:menupopup>
   <menu:menu menu:id=".uno:InsertBreakMenu" menu:label="">
    <menu:menupopup>
     <menu:menuitem menu:id=".uno:InsertRowBreak"/>
     <menu:menuitem menu:id=".uno:InsertColumnBreak"/>
    </menu:menupopup>
   </menu:menu>
   <menu:menuitem menu:id=".uno:InsertCell"/>
   <menu:menuitem menu:id=".uno:InsertRows"/>
   <menu:menuitem menu:id=".uno:InsertColumns"/>
   <menu:menuitem menu:id=".uno:Insert"/>
   <menu:menuitem menu:id=".uno:InsertSymbol"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:FunctionDialog"/>
   <menu:menuitem menu:id=".uno:FunctionBox"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:InsertAnnotation"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:InsertObjectChart"/>
  </menu:menupopup>
 </menu:menu>
 <menu:menu menu:id=".uno:FormatMenu" menu:label="">
  <menu:menupopup>
   <menu:menuitem menu:id=".uno:FormatCellDialog"/>
   <menu:menu menu:id=".uno:RowMenu" menu:label="">
    <menu:menupopup>
     <menu:menuitem menu:id=".uno:RowHeight"/>
     <menu:menuitem menu:id=".uno:SetOptimalRowHeight"/>
     <menu:menuitem menu:id=".uno:HideRow"/>
     <menu:menuitem menu:id=".uno:ShowRow"/>
    </menu:menupopup>
   </menu:menu>
   <menu:menu menu:id=".uno:ColumnMenu" menu:label="">
    <menu:menupopup>
     <menu:menuitem menu:id=".uno:ColumnWidth"/>
     <menu:menuitem menu:id=".uno:SetOptimalColumnWidth"/>
     <menu:menuitem menu:id=".uno:HideColumn"/>
     <menu:menuitem menu:id=".uno:ShowColumn"/>
    </menu:menupopup>
   </menu:menu>
   <menu:menu menu:id=".uno:SheetMenu" menu:label="">
    <menu:menupopup>
     <menu:menuitem menu:id=".uno:RenameTable"/>
     <menu:menuitem menu:id=".uno:Hide"/>
     <menu:menuitem menu:id=".uno:Show"/>
     <menu:menuitem menu:id=".uno:SheetRightToLeft"/>
    </menu:menupopup>
   </menu:menu>
   <menu:menuitem menu:id=".uno:ToggleMergeCells"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:PageFormatDialog"/>
   <menu:menuseparator/>
   <menu:menu menu:id=".uno:TransliterateMenu" menu:label="">
    <menu:menupopup>
     <menu:menuitem menu:id=".uno:ChangeCaseToUpper"/>
     <menu:menuitem menu:id=".uno:ChangeCaseToLower"/>
     <menu:menuitem menu:id=".uno:ChangeCaseToHalfWidth"/>
     <menu:menuitem menu:id=".uno:ChangeCaseToFullWidth"/>
     <menu:menuitem menu:id=".uno:ChangeCaseToHiragana"/>
     <menu:menuitem menu:id=".uno:ChangeCaseToKatakana"/>
    </menu:menupopup>
   </menu:menu>
   <menu:menu menu:id=".uno:ObjectAlign" menu:label="">
    <menu:menupopup>
     <menu:menuitem menu:id=".uno:CommonAlignHorizontalDefault"/>
     <menu:menuitem menu:id=".uno:CommonAlignLeft"/>
     <menu:menuitem menu:id=".uno:CommonAlignHorizontalCenter"/>
     <menu:menuitem menu:id=".uno:CommonAlignRight"/>
     <menu:menuitem menu:id=".uno:CommonAlignJustified"/>
     <menu:menuseparator/>
     <menu:menuitem menu:id=".uno:CommonAlignTop"/>
     <menu:menuitem menu:id=".uno:CommonAlignVerticalCenter"/>
     <menu:menuitem menu:id=".uno:CommonAlignBottom"/>
    </menu:menupopup>
   </menu:menu>
  </menu:menupopup>
 </menu:menu>
 <menu:menu menu:id=".uno:ToolsMenu" menu:label="">
  <menu:menupopup>
   <menu:menuseparator/>
   <menu:menu menu:id=".uno:CellContentsMenu" menu:label="">
    <menu:menupopup>
     <menu:menuitem menu:id=".uno:Calculate"/>
     <menu:menuitem menu:id=".uno:AutomaticCalculation"/>
     <menu:menuseparator/>
     <menu:menuitem menu:id=".uno:AutoComplete"/>
    </menu:menupopup>
   </menu:menu>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:ConfigureDialog"/>
   <menu:menuitem menu:id=".uno:OptionsTreeDialog"/>
  </menu:menupopup>
 </menu:menu>
 <menu:menu menu:id=".uno:DataMenu" menu:label="">
  <menu:menupopup>
   <menu:menuitem menu:id=".uno:DefineDBName"/>
   <menu:menuitem menu:id=".uno:SelectDB"/>
   <menu:menuitem menu:id=".uno:DataSort"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:TextToColumns"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:DataAreaRefresh"/>
  </menu:menupopup>
 </menu:menu>
 <menu:menu menu:id=".uno:WindowList" menu:label="">
  <menu:menupopup>
   <menu:menuitem menu:id=".uno:NewWindow"/>
   <menu:menuitem menu:id=".uno:CloseWin"/>
   <menu:menuseparator/>
   <menu:menuitem menu:id=".uno:SplitWindow"/>
   <menu:menuitem menu:id=".uno:FreezePanes"/>
  </menu:menupopup>
 </menu:menu>
 <menu:menu menu:id=".uno:HelpMenu" menu:label="">
  <menu:menupopup>
   <menu:menuitem menu:id=".uno:HelpIndex"/>
   <menu:menuitem menu:id=".uno:ExtendedHelp"/>
   <menu:menuitem menu:id=".uno:About"/>
   <menu:menuitem menu:id=".uno:ShowLicense"/>
  </menu:menupopup>
 </menu:menu>
</menu:menubar>
