=== sugar-activities/4439-activity/resources/basis-link/share/dtd/officedocument/1_0/toolbar.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--

  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
  
  Copyright 2008 by Sun Microsystems, Inc.
 
  OpenOffice.org - a multi-platform office productivity suite
 
  $RCSfile: toolbar.dtd,v $
 
  $Revision: 1.9 $
 
  This file is part of OpenOffice.org.
 
  OpenOffice.org is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License version 3
  only, as published by the Free Software Foundation.
 
  OpenOffice.org is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Lesser General Public License version 3 for more details
  (a copy is included in the LICENSE file that accompanied this code).
 
  You should have received a copy of the GNU Lesser General Public License
  version 3 along with OpenOffice.org.  If not, see
  <http://www.openoffice.org/license.html>
  for a copy of the LGPLv3 License.
 
-->
<!ENTITY % boolean "(true|false)">
<!ENTITY % numeric "CDATA">
<!ENTITY % alignment "(top|bottom|left|right)">
<!ENTITY % style "(symbol|text|symboltext)">
<!ELEMENT toolbar:toolbar (toolbar:toolbaritem | toolbar:toolbarspace | toolbar:toolbarbreak | toolbar:toolbarseparator)*>
<!ATTLIST toolbar:toolbar
	xmlns:toolbar CDATA #FIXED "http://openoffice.org/2001/toolbar"
	xmlns:xlink CDATA #FIXED "http://www.w3.org/1999/xlink"
>
<!ELEMENT toolbar:toolbaritem EMPTY>
<!ATTLIST toolbar:toolbaritem
	xlink:href CDATA #REQUIRED
	toolbar:visible %boolean; "true"
	toolbar:userdefined %boolean; "false"
	toolbar:text CDATA #IMPLIED
	toolbar:width %numeric; "0"
	toolbar:style CDATA #IMPLIED
	toolbar:bitmap CDATA #IMPLIED
	toolbar:helpid CDATA #IMPLIED
>
<!ELEMENT toolbar:toolbarspace EMPTY>
<!ELEMENT toolbar:toolbarbreak EMPTY>
<!ELEMENT toolbar:toolbarseparator EMPTY>
<!ELEMENT toolbar:toolbarlayouts (toolbar:toolbarlayout*)>
<!ATTLIST toolbar:toolbarlayouts
	xmlns:toolbar CDATA #FIXED "http://openoffice.org/2001/toolbar"
>
<!ELEMENT toolbar:toolbarlayout EMPTY>
<!ATTLIST toolbar:toolbarlayout
	toolbar:id CDATA #REQUIRED
	toolbar:floatingposleft %numeric; #IMPLIED
	toolbar:floatingpostop %numeric; #IMPLIED
	toolbar:floatinglines %numeric; "0"
	toolbar:dockinglines %numeric; "1"
	toolbar:align %alignment; "left"
	toolbar:visible %boolean; "false"
	toolbar:floating %boolean; "false"
	toolbar:style %style; "symbol"
	toolbar:userdefname CDATA #IMPLIED
>

=== sugar-activities/4439-activity/resources/basis-link/share/config/soffice.cfg/modules/swriter/toolbar/beginner.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE toolbar:toolbar PUBLIC "-//OpenOffice.org//DTD OfficeDocument 1.0//EN" "toolbar.dtd">
<toolbar:toolbar xmlns:toolbar="http://openoffice.org/2001/toolbar" xmlns:xlink="http://www.w3.org/1999/xlink">
 <toolbar:toolbaritem xlink:href=".uno:CharFontName" toolbar:helpid=".uno:CharFontName"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:Shrink" toolbar:helpid=".uno:Shrink"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:Grow" toolbar:helpid=".uno:Grow"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:Bold" toolbar:helpid=".uno:Bold"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:Underline" toolbar:helpid=".uno:Underline"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:Italic" toolbar:helpid=".uno:Italic"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:InsertGraphic" toolbar:helpid=".uno:InsertGraphic"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:Gallery" toolbar:text="Galerie" toolbar:helpid=".uno:Gallery"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:InsertDraw" toolbar:helpid=".uno:InsertDraw"/>
</toolbar:toolbar>

=== sugar-activities/4439-activity/resources/basis-link/share/config/soffice.cfg/modules/scalc/toolbar/formatobjectbar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE toolbar:toolbar PUBLIC "-//OpenOffice.org//DTD OfficeDocument 1.0//EN" "toolbar.dtd">
<toolbar:toolbar xmlns:toolbar="http://openoffice.org/2001/toolbar" xmlns:xlink="http://www.w3.org/1999/xlink">
 <toolbar:toolbaritem xlink:href=".uno:DesignerDialog" toolbar:helpid="helpid:5539"/>
 <toolbar:toolbaritem xlink:href=".uno:StyleApply" toolbar:visible="false" toolbar:helpid="helpid:5552"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:CharFontName" toolbar:helpid="helpid:10007"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:FontHeight" toolbar:helpid="helpid:10015"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:Bold" toolbar:visible="false" toolbar:helpid="helpid:10009"/>
 <toolbar:toolbaritem xlink:href=".uno:Italic" toolbar:visible="false" toolbar:helpid="helpid:10008"/>
 <toolbar:toolbaritem xlink:href=".uno:Underline" toolbar:visible="false" toolbar:helpid="helpid:10014"/>
 <toolbar:toolbaritem xlink:href=".uno:UnderlineDouble" toolbar:visible="false" toolbar:helpid="helpid:26648"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:AlignLeft" toolbar:visible="false" toolbar:helpid="helpid:26371"/>
 <toolbar:toolbaritem xlink:href=".uno:AlignHorizontalCenter" toolbar:visible="false" toolbar:helpid="helpid:26373"/>
 <toolbar:toolbaritem xlink:href=".uno:AlignRight" toolbar:visible="false" toolbar:helpid="helpid:26372"/>
 <toolbar:toolbaritem xlink:href=".uno:AlignBlock" toolbar:visible="false" toolbar:helpid="helpid:26374"/>
 <toolbar:toolbaritem xlink:href=".uno:ToggleMergeCells" toolbar:helpid="helpid:26581"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:ParaLeftToRight" toolbar:helpid="helpid:10950"/>
 <toolbar:toolbaritem xlink:href=".uno:ParaRightToLeft" toolbar:helpid="helpid:10951"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:TextdirectionLeftToRight" toolbar:helpid="helpid:10907"/>
 <toolbar:toolbaritem xlink:href=".uno:TextdirectionTopToBottom" toolbar:helpid="helpid:10908"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:AlignTop" toolbar:visible="false" toolbar:helpid="helpid:26375"/>
 <toolbar:toolbaritem xlink:href=".uno:AlignVCenter" toolbar:visible="false" toolbar:helpid="helpid:26377"/>
 <toolbar:toolbaritem xlink:href=".uno:AlignBottom" toolbar:visible="false" toolbar:helpid="helpid:26376"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:NumberFormatCurrency" toolbar:visible="false" toolbar:helpid="helpid:26045"/>
 <toolbar:toolbaritem xlink:href=".uno:NumberFormatPercent" toolbar:helpid="helpid:26046"/>
 <toolbar:toolbaritem xlink:href=".uno:NumberFormatDate" toolbar:visible="false" toolbar:helpid="helpid:26053"/>
 <toolbar:toolbaritem xlink:href=".uno:NumberFormatScientific" toolbar:visible="false" toolbar:helpid="helpid:26055"/>
 <toolbar:toolbaritem xlink:href=".uno:NumberFormatStandard" toolbar:visible="false" toolbar:helpid="helpid:26052"/>
 <toolbar:toolbaritem xlink:href=".uno:NumberFormatIncDecimals" toolbar:helpid="helpid:26057"/>
 <toolbar:toolbaritem xlink:href=".uno:NumberFormatDecDecimals" toolbar:helpid="helpid:26058"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:DecrementIndent" toolbar:visible="false" toolbar:helpid="helpid:10461"/>
 <toolbar:toolbaritem xlink:href=".uno:IncrementIndent" toolbar:visible="false" toolbar:helpid="helpid:10462"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:SetBorderStyle" toolbar:visible="false" toolbar:helpid="helpid:10187"/>
 <toolbar:toolbaritem xlink:href=".uno:BackgroundColor" toolbar:visible="false" toolbar:helpid="helpid:10185"/>
 <toolbar:toolbaritem xlink:href=".uno:Color" toolbar:visible="false" toolbar:helpid="helpid:10017"/>
 <toolbar:toolbaritem xlink:href=".uno:LineStyle" toolbar:visible="false" toolbar:helpid="helpid:10200"/>
 <toolbar:toolbaritem xlink:href=".uno:FrameLineColor" toolbar:visible="false" toolbar:helpid="helpid:10201"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:InsertRows" toolbar:visible="false" toolbar:helpid="helpid:26267"/>
 <toolbar:toolbaritem xlink:href=".uno:InsertColumns" toolbar:visible="false" toolbar:helpid="helpid:26268"/>
 <toolbar:toolbaritem xlink:href=".uno:DeleteRows" toolbar:visible="false" toolbar:helpid="helpid:26236"/>
 <toolbar:toolbaritem xlink:href=".uno:DeleteColumns" toolbar:visible="false" toolbar:helpid="helpid:26237"/>
</toolbar:toolbar>

=== sugar-activities/4439-activity/resources/basis-link/share/config/soffice.cfg/modules/swriter/toolbar/standardbar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE toolbar:toolbar PUBLIC "-//OpenOffice.org//DTD OfficeDocument 1.0//EN" "toolbar.dtd">
<toolbar:toolbar xmlns:toolbar="http://openoffice.org/2001/toolbar" xmlns:xlink="http://www.w3.org/1999/xlink">
 <toolbar:toolbaritem xlink:href=".uno:AddDirect" toolbar:helpid="5537"/>
 <toolbar:toolbaritem xlink:href=".uno:NewDoc" toolbar:visible="false" toolbar:helpid="5500"/>
 <toolbar:toolbaritem xlink:href=".uno:Open" toolbar:helpid="5501"/>
 <toolbar:toolbaritem xlink:href=".uno:Save" toolbar:helpid="5505"/>
 <toolbar:toolbaritem xlink:href=".uno:SaveAs" toolbar:visible="false" toolbar:helpid="5502"/>
 <toolbar:toolbaritem xlink:href=".uno:ExportDirectToPDF" toolbar:helpid="6674"/>
 <toolbar:toolbaritem xlink:href=".uno:PrintDefault" toolbar:visible="false" toolbar:helpid="5509"/>
 <toolbar:toolbaritem xlink:href=".uno:SendMail" toolbar:visible="false" toolbar:helpid="5331"/>
 <toolbar:toolbaritem xlink:href=".uno:BackgroundColor" toolbar:helpid=".uno:BackgroundColor"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:CharFontName" toolbar:helpid=".uno:CharFontName"/>
 <toolbar:toolbaritem xlink:href=".uno:FontHeight" toolbar:helpid=".uno:FontHeight"/>
 <toolbar:toolbaritem xlink:href=".uno:Bold" toolbar:helpid=".uno:Bold"/>
 <toolbar:toolbaritem xlink:href=".uno:Italic" toolbar:helpid=".uno:Italic"/>
 <toolbar:toolbaritem xlink:href=".uno:Underline" toolbar:helpid=".uno:Underline"/>
 <toolbar:toolbaritem xlink:href=".uno:LeftPara" toolbar:helpid=".uno:LeftPara"/>
 <toolbar:toolbaritem xlink:href=".uno:OpenUrl" toolbar:visible="false"/>
 <toolbar:toolbaritem xlink:href=".uno:CenterPara" toolbar:helpid=".uno:CenterPara"/>
 <toolbar:toolbaritem xlink:href=".uno:RightPara" toolbar:helpid=".uno:RightPara"/>
 <toolbar:toolbaritem xlink:href=".uno:JustifyPara" toolbar:helpid=".uno:JustifyPara"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:PrintPreview" toolbar:helpid="5325"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:SpellingAndGrammarDialog" toolbar:helpid="20622"/>
 <toolbar:toolbaritem xlink:href=".uno:SpellOnline" toolbar:helpid="12021"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:Cut" toolbar:helpid="5710"/>
 <toolbar:toolbaritem xlink:href=".uno:Copy" toolbar:helpid="5711"/>
 <toolbar:toolbaritem xlink:href=".uno:Paste" toolbar:helpid="5712"/>
 <toolbar:toolbaritem xlink:href=".uno:FormatPaintbrush" toolbar:visible="false" toolbar:helpid="5715"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:Undo" toolbar:helpid="5701"/>
 <toolbar:toolbaritem xlink:href=".uno:Redo" toolbar:helpid="5700"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:HyperlinkDialog" toolbar:visible="false" toolbar:helpid="5678"/>
 <toolbar:toolbaritem xlink:href=".uno:InsertTable" toolbar:visible="false" toolbar:helpid="20330"/>
 <toolbar:toolbaritem xlink:href=".uno:InsertDraw" toolbar:helpid="10244"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:SearchDialog" toolbar:helpid="5961"/>
 <toolbar:toolbaritem xlink:href=".uno:Navigator" toolbar:visible="false" toolbar:helpid="10366"/>
 <toolbar:toolbaritem xlink:href=".uno:Gallery" toolbar:visible="false" toolbar:helpid="5960"/>
 <toolbar:toolbaritem xlink:href=".uno:ViewDataSourceBrowser" toolbar:helpid="6660"/>
 <toolbar:toolbaritem xlink:href=".uno:ControlCodes" toolbar:visible="false" toolbar:helpid="20224"/>
 <toolbar:toolbaritem xlink:href=".uno:Zoom" toolbar:visible="false" toolbar:helpid="10000"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:HelpIndex"/>
 <toolbar:toolbaritem xlink:href=".uno:ExtendedHelp" toolbar:visible="false" toolbar:helpid="5402"/>
</toolbar:toolbar>

=== sugar-activities/4439-activity/resources/basis-link/share/config/soffice.cfg/modules/swriter/toolbar/viewerbar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE toolbar:toolbar PUBLIC "-//OpenOffice.org//DTD OfficeDocument 1.0//EN" "toolbar.dtd">
<toolbar:toolbar xmlns:toolbar="http://openoffice.org/2001/toolbar" xmlns:xlink="http://www.w3.org/1999/xlink">
 <toolbar:toolbaritem xlink:href=".uno:SaveAs" toolbar:helpid="5502"/>
 <toolbar:toolbaritem xlink:href=".uno:ExportDirectToPDF" toolbar:helpid="6674"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:EditDoc" toolbar:visible="false" toolbar:helpid="helpid:6312"/>
 <toolbar:toolbaritem xlink:href=".uno:SendMail" toolbar:helpid="helpid:5331"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:PrintDefault" toolbar:helpid="helpid:5509"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:Copy" toolbar:helpid="helpid:5711"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:SearchDialog" toolbar:helpid="helpid:5961"/>
 <toolbar:toolbaritem xlink:href=".uno:Navigator" toolbar:helpid="helpid:10366"/>
 <toolbar:toolbarseparator/>
 <toolbar:toolbaritem xlink:href=".uno:Zoom" toolbar:helpid="helpid:10000"/>
</toolbar:toolbar>
